### ISSUE TITLE
kernel-module-injector fails on Ubuntu 18.04 & 20.04 (Rancher 2.5.1)

### ISSUE THREAD

**Issue by fairEnough83** [piraeusdatastore/piraeus-operator#134]
Good day!

I'm getting the following log output from kernel-module-injector container of the üiraeus-op-ns-node-xxx pod. 

    SORRY, kernel makefile not found.
    You need to tell me a correct KDIR,
    Or install the neccessary kernel source packages.

Makefile:125: recipe for target 'check-kdir' failed
make: *** [check-kdir] Error 1

Could not find the expexted *.ko, see stderr for more details

Isn't the kernel source package installed by the  kernel-module-injector? Or what I'm doing wrong

Thank you in advance.

Stephan

**Comment by WanzenBug** [comment]
Hello,

The kernel headers/sources are _not_ installed by the kernel-module-injector. Instead the injector mounts the host directory `/usr/src` and tries to find the source there. So you need to install the kernel sources on the host machine.

**Comment by fairEnough83** [comment]
Dear WanzenBug,

Thanks, my workaround was similar. I installed everything on the host system and disabled the kernel-module-injector, but good to know that only kernel sources are needed.

Thank you,
Stephan

**Comment by WanzenBug** [comment]
In that case, please make sure to set DRBDs `usermode_helper` parameter to `disabled`. You can verify that using

```
$ cat /sys/module/drbd/parameters/usermode_helper
disabled
```

To set the parameter use `modprobe drbd usermode_helper=disabled` or make it permanent:

```
# echo "options drbd usermode_helper=disabled" > /etc/modprobe.d/drbd.conf"
```

If you do not set this parameter, DRBD will try to call the `drbdadm` command on most state changes, which then fails because the resource definition file is only available from inside the Piraeus containers. DRBD will then abort the state change, leaving you with a bunch of "StandAlone" resources

**Comment by fairEnough83** [comment]
thanks

**Comment by kintarowins** [comment]
this is still happening, I'm using Amazon Linux 2

**Comment by WanzenBug** [comment]
Then you likely need to install the kernel headers on the host. I don't know how that packages is called on AL2, probably similar to RHEL, so try installing `kernel-devel`.
