### ISSUE TITLE
ERROR LINSTOR/Controller - SYSTEM - Database initialization error [Report number 60B2A483-00000-000000]

### ISSUE THREAD

**Issue by tobg** [piraeusdatastore/piraeus-operator#184]
Hello

After upgrade our k8s helm based installation to operator v1.5.0 we get following error for cs-controller.
 Initializing the etcd database
20:31:02.094 [Main] ERROR LINSTOR/Controller - SYSTEM - Database initialization error [Report number 60B2A483-00000-000000]

Report # cannot be resolved because controller crashes.

With piraeus-server version 1.11.1 everting works fine. If we use the new version 1.12.3 we got the above error.

Any hint on how to resolve this would be appreciated. Thanks.

**Comment by WanzenBug** [comment]
I guess it could be something similar to https://github.com/piraeusdatastore/piraeus/issues/79

To confirm, we would need the error report. Since the container keeps crashing the best way to get to it is:
* Stop the operator deployment (scale to 0 replicas)
* Edit the controller deployment to use a persistent volume (hostpath for example) for the `/var/log/linstor-controller` directory
* Wait for the above error, there should be a `Error-Report-XXXXXXX.log` file in the persistent volume

**Comment by tobg** [comment]
It was the same issue. I had some orphan snapshots. After I get rid of it I was able to upgrade to version 1.12.3.

Thank you very much! :)
