### ISSUE TITLE
default IP modify doesnt work

### ISSUE THREAD

**Issue by muecahit94** [piraeusdatastore/piraeus-operator#187]
Hi, 
on the new clusters (with the new piraeus versions), we cannot change the default IP with the command:
`linstor node interface modify <node name> default --ip 192.168.xxx.xxx`
On older clusters, where we have an older piraeus version it working.
First it looks like the IP change worked, but after few seconds it turns back to the previous IP.

Background is, we use separate NIC for internal data transfer and want to use that NIC as default for DRBD traffic.

Can you pls help us with that problem.

**Comment by WanzenBug** [comment]
Hi!

I guess this was caused by the change made in #170. With this change, the operator will always compare the expected address with the currently registered address and update if they are different. This helps in cases were the controller pod switches IPs and also if for some reason a node would change IP (I guess that second one is not very likely).

What you can do instead of modifying the existing interface is to add a new one `linstor node interface create <nodename> data-nic 192.168.xxx.xxx` and instruct linstor to use it: `linstor node set-property <nodename> PrefNic data-nic`

**Comment by phoenix-bjoern** [comment]
@WanzenBug Thanks for the advise. How can we verify the newly configured device is actually used? `linstor n l` still lists the previous IP.

**Comment by WanzenBug** [comment]
The information in `linstor n l` only shows the IP used for "control" traffic between linstor node. If you create a resource (PV) you can manually check the DRBD resources by `kubectl exec` into a satellite pod (`piraeus-op-ns-node-xxxxx`) and running `drbdadm dump <pv-name>`. The output will contain a section like:
```
    connection {
        host worker1         address         ipv4 10.10.10.1:7002;
        host worker2         address         ipv4 10.10.10.2:7002;
    }
    connection {
        host worker1         address         ipv4 10.10.10.1:7002;
        host worker3         address         ipv4 10.10.10.3:7002;
    }

```

**Comment by muecahit94** [comment]
Thank you this worked for us.
As a sidenode, we had some troubles with the volumes on our big cluster, on small clusters with a few drbd-volumes it worked very smooth, but on a big cluster with many drbd-volumes some of the volumes failed and turned to outdated(red) and the pods had to be restarted, that it turns back to "green".
