### ISSUE TITLE
Use existing kubernetes etcd bd

### ISSUE THREAD

**Issue by AndreiPaulau** [piraeusdatastore/piraeus-operator#197]
Hi gents!

I'm curious, I have 3 dedicated master nodes with 3 etcd instances.
I'm not very existed about supporting 2 separate but vital etcd setups. :)
1. Is there an option to use exisitng etcd cluster for piraeus setup (like mentioned in docs, we can use postgre)?
2. What should prevent me to do this? :)

If this possible, would be great if you can share some example line

Many thanks!

**Comment by JoelColledge** [comment]
Hi!

Your desire to not need to maintain 2 etcd clusters is understandable :-)

This has been considered, but there were good reasons not to recommend it. Perhaps @kermat could fill in the details?

It is also possible that Linstor will be adapted so that it can store its data in Kubernetes Custom Resources. This would remove the need for an additional database.

**Comment by kermat** [comment]
I believe the decision (made 3+ years ago) to deploy our own etcd was based in security. Kubernetes' documentation suggests only the Kubernetes API server have access to Kubernetes' etcd, since access to it is basically root access to the entire cluster.

**Comment by AndreiPaulau** [comment]
Fair enough regarding security access =)
Managing own baremetal cluster sometimes blinds and security is not so vital in secured perimiter.
Closing then? many thanks!
