### ISSUE TITLE
piraeus-ha-controller:v1.2.0 & 1.1.4 fail due to parse of `drbdsetup status --json`

### ISSUE THREAD

**Issue by zeph** [piraeusdatastore/piraeus-operator#587]
I updated to the latest version of drbd-utils after spotting https://github.com/LINBIT/drbd-utils/issues/10
...I attempted to move also from piraeus-operator `v2.3.0` to `satellite-daemonset` as apparently it was bumping the image of the controller... nothing, the container are failing due to the `--json` flag not being recognized by `drbdsetup status`

```
ha-controller-zfwpm ha-controller I0106 19:15:12.279618       1 agent.go:201] version: v1.2.0
ha-controller-zfwpm ha-controller I0106 19:15:12.279736       1 agent.go:202] node: blade2
ha-controller-zfwpm ha-controller I0106 19:15:12.279830       1 agent.go:228] waiting for caches to sync
ha-controller-zfwpm ha-controller I0106 19:15:12.380267       1 agent.go:230] caches synced
ha-controller-zfwpm ha-controller I0106 19:15:12.380308       1 agent.go:253] starting reconciliation
ha-controller-zfwpm ha-controller E0106 19:15:12.380471       1 run.go:74] "command failed" err="failed to execute drbdsetup status --json: exit status 20"
- ha-controller-zfwpm › ha-controller
ha-controller-lx4d2 ha-controller I0106 19:15:12.879968       1 agent.go:201] version: v1.2.0
ha-controller-lx4d2 ha-controller I0106 19:15:12.880193       1 agent.go:202] node: blade1
ha-controller-lx4d2 ha-controller I0106 19:15:12.880421       1 agent.go:228] waiting for caches to sync
ha-controller-lx4d2 ha-controller I0106 19:15:12.981142       1 agent.go:230] caches synced
ha-controller-lx4d2 ha-controller I0106 19:15:12.981172       1 agent.go:253] starting reconciliation
ha-controller-lx4d2 ha-controller E0106 19:15:12.981332       1 run.go:74] "command failed" err="failed to execute drbdsetup status --json: exit status 20"
- ha-controller-lx4d2 › ha-controller
ha-controller-vk8d9 ha-controller I0106 19:15:07.544973       1 agent.go:201] version: v1.2.0
ha-controller-vk8d9 ha-controller I0106 19:15:07.545114       1 agent.go:202] node: blade3
ha-controller-vk8d9 ha-controller I0106 19:15:07.545232       1 agent.go:228] waiting for caches to sync
ha-controller-vk8d9 ha-controller I0106 19:15:07.645699       1 agent.go:230] caches synced
ha-controller-vk8d9 ha-controller I0106 19:15:07.645735       1 agent.go:253] starting reconciliation
ha-controller-vk8d9 ha-controller E0106 19:15:07.645945       1 run.go:74] "command failed" err="failed to execute drbdsetup status --json: exit status 20"
```

**Comment by WanzenBug** [comment]
As the upstream issue indicates, this happens because you have DRBD 8 loaded. But we need DRBD 9. This should actually be done by Piraeus.

But if you use Ubuntu, and install drbd-utils on the host, Ubuntu for some reason enables the `drbd.service` systemd unit: this then causes DRBD 8 to be loaded before the Kubernetes resources have a chance. So please disable that service and use the [DRBD loader](https://github.com/piraeusdatastore/piraeus-operator/blob/v2/docs/how-to/drbd-loader.md) from Piraeus.

**Comment by zeph** [comment]
@WanzenBug I will! thanks for the detailed follow up / reply... really appreciated

**Comment by the-xentropy** [comment]
If you disabled this service and it's still happening to you:

First, verify that it's the kernel module:
1. First run `sudo rmmod drbd` to unload the current kernel module
2. Restart (read: delete so the operator recreates it) the `<node name>` pod in your piraeus namespace so it reloads your drbd module with the correct version.
3. Restart the ha-controller daemon set pod for the same node
4. If the above works, it was definitely a mismatched kernel module. You want the pods to manage it, not the host.

For permanence of solution:
1. systemctl stop drbd
2. systemctl disable drbd
3. Check if you have an init script at `/etc/init.d/drbd` - for I guess compatability reasons ubuntu installed both an init script and a systemd service, but this means if you disable the service the init.d script still appears to run. I moved it to another folder and rebooted and lo and behold - glorious success.
4. If you already did the temporary steps, you don't have to reboot - otherwise, reboot.
